<a href="https://colab.research.google.com/github/MarcinHrynkiewiczSudnik/Python3/blob/main/01_wprowadzenie_02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [3]:
np.linalg.norm(v1)

4.0

In [4]:
v2 = np.array([-1, 4])
v2

array([-1,  4])

In [5]:
np.linalg.norm(v2)

4.123105625617661

In [6]:
v3 = np.array([-10,10,14])
np.linalg.norm(v3)

19.8997487421324

Odległość dwóch punktów na płaszczyźnie

In [7]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

Odległość dwóch punktów w przestrzeni

In [8]:
p = np.array([3,0,1])
q = np.array([0,4,3])

np.linalg.norm(p-q)

5.385164807134504

Mnożenie macierzy

In [10]:
X = np.array([[5,3],[3,9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [11]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [12]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])

Y = np.array([[2, 1, -1], 
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [13]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik macierzy

In [15]:
A = np.array([[2, 4], [-1, 3]])
np.linalg.det(A)
round(np.linalg.det(A))

10

Ślad macierzy

In [16]:
A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa

In [17]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [18]:
np.eye(2, dtype='int')

array([[1, 0],
       [0, 1]])

Macierz odwrotna

In [19]:
A = np.array([[2, 4], [-1, 3]])
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [20]:
np.dot(A, B)

array([[1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 1.00000000e+00]])

In [21]:
np.set_printoptions(precision=4, suppress=True)
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [22]:
A @ B

array([[1., 0.],
       [0., 1.]])

In [23]:
B @ A

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [25]:
A = np.array([[2, 1, -1], [0, -1, 2]])
A

array([[ 2,  1, -1],
       [ 0, -1,  2]])

In [26]:
A.T

array([[ 2,  0],
       [ 1, -1],
       [-1,  2]])

Rozwiązywanie układów równań

2x + 4y = 10,
x - y = -1




In [27]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [28]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [29]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.1667  0.6667]
 [ 0.1667 -0.3333]]


In [30]:
X = np.dot(A_inv, B)
print(X)

[[1.]
 [2.]]
