<a href="https://colab.research.google.com/github/MarcinHrynkiewiczSudnik/Python3/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Colab")

Hello Colab


In [2]:
import numpy as np


In [4]:
x = np.array([1,3])
x

array([1, 3])

In [5]:
print(x)

[1 3]


In [6]:
type(x)

numpy.ndarray

In [7]:
x.ndim

1

In [8]:
x.shape

(2,)

In [9]:
x.size

2

In [10]:
x.dtype

dtype('int64')

In [12]:
x = np.array([1.3, 2.4, 3.5])
print(x)
x.dtype

[1.3 2.4 3.5]


dtype('float64')

In [15]:
x = np.array([[1,2], [-3,-5]])


In [16]:
x.ndim

2

In [17]:
x.shape

(2, 2)

In [18]:
x = np.array([[1,2,4], [5,3,1]])
print(x)

[[1 2 4]
 [5 3 1]]


In [19]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[4,1,3],
      [4,2,1]]
     ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [20]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [26]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [28]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [29]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [30]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [35]:
A + B

array([6, 0, 7, 4])

In [36]:
A - B

array([0, 2, 1, 0])

In [37]:
A * B

array([ 9, -1, 12,  4])

In [38]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [39]:
B / A

array([ 1.  , -1.  ,  0.75,  1.  ])

In [40]:
A + 4

array([7, 5, 8, 6])

In [41]:
A * 1.8

array([5.4, 1.8, 7.2, 3.6])

In [42]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [43]:
np.dot(X, Y)


array([[  3,   6],
       [-12,   0]])

In [44]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [45]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [46]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [47]:
Y @ X

array([[ 6, 18],
       [-5, -3]])